/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import java.util.ArrayList;
import deepspace.HangarToUI;
import deepspace.WeaponToUI;

/**
 *
 * @author laura
 */
public class HangarView extends javax.swing.JPanel {

    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
    }
    
    public void setHangar(HangarToUI h){
        maxElements.setText(Integer.toString(h.getMaxElements()));
        weaponsPanel.removeAll();
        ArrayList<WeaponToUI> weapons= h.getWeapons();
        WeaponView wView;
        for(WeaponToUI w: weapons){
            wView = new WeaponView();
            wView.setWeapon(w);
            weaponsPanel.add(wView);
        }
        repaint();
        revalidate();             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WeaponScroll = new javax.swing.JScrollPane();
        weaponsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maxElements = new javax.swing.JLabel();

        WeaponScroll.setViewportView(weaponsPanel);

        jLabel1.setText("Capacidad: ");

        maxElements.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(maxElements))
                    .addComponent(WeaponScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maxElements))
                .addGap(36, 36, 36)
                .addComponent(WeaponScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane WeaponScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maxElements;
    private javax.swing.JPanel weaponsPanel;
    // End of variables declaration//GEN-END:variables
}
