/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import java.util.ArrayList;
import deepspace.HangarToUI;
import deepspace.ShieldToUI;
import deepspace.WeaponToUI;
import java.awt.Component;

/**
 *
 * @author laura
 */
public class HangarView extends javax.swing.JPanel {

    /**
     * Creates new form HangarView
     */
    public HangarView() {
        initComponents();
    }
    
    public void setHangar(HangarToUI h){
        maxElements.setText(Integer.toString(h.getMaxElements()));
        weaponsPanel.removeAll();
        ArrayList<WeaponToUI> weapons= h.getWeapons();
        WeaponView wView;
        for(WeaponToUI w: weapons){
            wView = new WeaponView();
            wView.setWeapon(w);
            weaponsPanel.add(wView);
        }
        
        shieldsPanel.removeAll();
        ArrayList<ShieldToUI> shields = h.getShieldBoosters();
        ShieldBoosterView sView = new ShieldBoosterView();
        for(ShieldToUI s: shields){
            sView = new ShieldBoosterView();
            sView.setShieldBooster(s);
            shieldsPanel.add(sView);
        }
            
        repaint();
        revalidate();             
    }
    
    ArrayList<Integer> getSelectedShields (){
        ArrayList<Integer> selectedShields = new ArrayList();
        int i = 0;
        for (Component c : shieldsPanel.getComponents()){
            if(((ShieldBoosterView) c).isSelected()){
                selectedShields.add(i);
            }
            i++;
            
        }
        return selectedShields;
    }
    
    ArrayList<Integer> getSelectedWeapons (){
        ArrayList<Integer> selectedWeapons = new ArrayList();
        int i = 0;
        for (Component c : weaponsPanel.getComponents()){
            if(((WeaponView) c).isSelected()){
                selectedWeapons.add(i);}
            i++;
            
        }
        return selectedWeapons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maxElements = new javax.swing.JLabel();
        weaponsScroll = new javax.swing.JScrollPane();
        weaponsPanel = new javax.swing.JPanel();
        shieldsScroll = new javax.swing.JScrollPane();
        shieldsPanel = new javax.swing.JPanel();

        setBorder(null);

        jLabel1.setText("Capacidad: ");

        maxElements.setText("jLabel2");

        weaponsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Armas"));
        weaponsScroll.setViewportView(weaponsPanel);

        shieldsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Escudos"));
        shieldsScroll.setViewportView(shieldsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(maxElements))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(weaponsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shieldsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maxElements))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shieldsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(weaponsScroll))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maxElements;
    private javax.swing.JPanel shieldsPanel;
    private javax.swing.JScrollPane shieldsScroll;
    private javax.swing.JPanel weaponsPanel;
    private javax.swing.JScrollPane weaponsScroll;
    // End of variables declaration//GEN-END:variables
}
