/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;
import View.View;
import controller.Controller;
import java.util.ArrayList;
//prueba
import deepspace.ShieldToUI;
import deepspace.WeaponToUI;
import deepspace.LootToUI;
import deepspace.NumericDamageToUI;
import deepspace.HangarToUI;

/**
 *
 * @author samuel
 */
public class MainView extends javax.swing.JFrame implements View{
    
     static Controller controller;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                controller.finish(0);
            }
        });
        
        setLocationRelativeTo(null);
    }
    
    public ArrayList<String> getNames(){
        Names n = new Names(this);
        return n.getNames();
    }
    
    
    @Override
    public void updateView(){
//        ShieldToUI escudoprueba = controller.dameUnEscudoPrueba();
//        ShieldBoosterView vistaescudoprueba = new ShieldBoosterView();
//        vistaescudoprueba.setShieldBooster(escudoprueba);
//        panelprueba.add(vistaescudoprueba);

        NumericDamageToUI np =controller.dameUnNumericoPrueba();
        NumericDamageView nd = new NumericDamageView();
        nd.setNumericDamage(np);
        panelprueba.add(nd);
        
//        WeaponToUI ap = controller.dameUnArmaPrueba();
//        WeaponView vap = new WeaponView();
//        vap.setWeapon(ap);
//        panelprueba2.add(vap);

        HangarToUI hp = controller.dameUnHangarPrueba();
        HangarView hview = new HangarView();
        hview.setHangar(hp);
        panelprueba2.add(hview);
        
        LootToUI lp = controller.dameUnBotinPrueba();
        LootView vlp = new LootView();
        vlp.setLoot(lp);
        panelprueba3.add(vlp);
        
        repaint();
        revalidate();
        
        
    }
    
    public void setController(Controller c){
        controller=c;
    }
    
    @Override
    public void showView(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprueba = new javax.swing.JPanel();
        panelprueba2 = new javax.swing.JPanel();
        panelprueba3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelprueba.setLayout(new java.awt.BorderLayout());

        panelprueba2.setLayout(new java.awt.BorderLayout());

        panelprueba3.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(panelprueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 444, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelprueba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelprueba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(panelprueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(panelprueba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(panelprueba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelprueba;
    private javax.swing.JPanel panelprueba2;
    private javax.swing.JPanel panelprueba3;
    // End of variables declaration//GEN-END:variables
}
