/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;
import java.awt.Component;
import deepspace.SpaceStationToUI;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import deepspace.HangarToUI;
import deepspace.DamageToUI;
import java.util.ArrayList;
/**
 *
 * @author laura
 */
public class SpaceStationView extends javax.swing.JPanel {
    
    
    private HangarView hv;
    /**
     * Creates new form SpaceStationView
     */
    public SpaceStationView() {
        initComponents();
        
        hv = new HangarView();
        
    }
    
    ArrayList<Integer> getSelectedShields (){
        ArrayList<Integer> selectedShields = new ArrayList();
        int i = 0;
        for (Component c : shieldsPanel.getComponents()){
            if(((ShieldBoosterView) c).isSelected()){
                selectedShields.add(i);}
            i++;
            
        }
        return selectedShields;
    }
    

    
    ArrayList<Integer> getSelectedWeapons (){
        ArrayList<Integer> selectedWeapons = new ArrayList();
        int i = 0;
        for (Component c : weaponsPanel.getComponents()){
            if(((WeaponView) c).isSelected()){
                selectedWeapons.add(i);}
            i++;
            
        }
        return selectedWeapons;
    }
    

    
    boolean areElementsSelected(){
        ArrayList<Integer> aux1 = getSelectedShields ();
        ArrayList<Integer> aux2 = getSelectedWeapons ();
        return((!aux1.isEmpty())||!aux2.isEmpty());
    }
    
    public void ocultarDamage(){
        damagePanel.setVisible(MainView.controller.getUIversion().getCurrentStation().getPendingDamage()!=null);
    }
        
 
    
    public void setSpaceStation(SpaceStationToUI st){
        nameLabel.setText(st.getName());
        fuelLabel.setText(Float.toString(st.getFuelUnits()));
        powerLabel.setText(Float.toString(st.getAmmoPower()));
        medalsLabel.setText(Integer.toString(st.getnMedals()));
        shieldPLabel.setText(Float.toString(st.getShieldPower()));
        
        weaponsPanel.removeAll();
        ArrayList<WeaponToUI> weapons = st.getWeapons();
        WeaponView wView = new WeaponView();
        for(WeaponToUI w: weapons){
            wView = new WeaponView();
            wView.setWeapon(w);
            weaponsPanel.add(wView);
        }   
        
        shieldsPanel.removeAll();
        ArrayList<ShieldToUI> shields = st.getShieldBoosters();
        ShieldBoosterView sView = new ShieldBoosterView();
        for(ShieldToUI s: shields){
            sView = new ShieldBoosterView();
            sView.setShieldBooster(s);
            shieldsPanel.add(sView);
        }
        
        HangarToUI h = st.getHangar();
        if(h!=null){
            hv.setHangar(h);
            hangarPanel.add(hv);
        } else
            hangarPanel.removeAll();
        damagePanel.removeAll();
        DamageToUI d = st.getPendingDamage();
        if(d!=null){
            DamageView dv = new DamageView();
            dv.setDamage(d);
            damagePanel.add(dv);
        }
        
        repaint();
        revalidate(); 
        
    }
//    public void updateView(){
//        jbDiscard.setEnabled(areElementsSelected());
//        jbMount.setEnabled(areElementsSelected());
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        fuelLabel = new javax.swing.JLabel();
        powerLabel = new javax.swing.JLabel();
        weaponsScroll = new javax.swing.JScrollPane();
        weaponsPanel = new javax.swing.JPanel();
        hangarPanel = new javax.swing.JPanel();
        damagePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        shieldPLabel = new javax.swing.JLabel();
        medalsLabel = new javax.swing.JLabel();
        shieldsScroll = new javax.swing.JScrollPane();
        shieldsPanel = new javax.swing.JPanel();
        jbDiscard = new javax.swing.JButton();
        jbMount = new javax.swing.JButton();
        jbDiscardHangar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Estación Espacial"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Combustible:");

        jLabel3.setText("Potencia:");

        nameLabel.setText("jLabel5");

        fuelLabel.setText("jLabel6");

        powerLabel.setText("jLabel7");

        weaponsScroll.setBorder(javax.swing.BorderFactory.createTitledBorder("Armas Montadas"));
        weaponsScroll.setViewportView(weaponsPanel);

        hangarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar"));

        damagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Daño pendiente"));

        jLabel4.setText("Potencia de escudo:");

        jLabel5.setText("Medallas");

        shieldPLabel.setText("jLabel6");

        medalsLabel.setText("jLabel7");

        shieldsScroll.setBorder(javax.swing.BorderFactory.createTitledBorder("Potenciadores de escudos montados"));
        shieldsScroll.setViewportView(shieldsPanel);

        jbDiscard.setText("Descartar");
        jbDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDiscardActionPerformed(evt);
            }
        });

        jbMount.setText("Montar");
        jbMount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMountActionPerformed(evt);
            }
        });

        jbDiscardHangar.setText("Descartar Hangar");
        jbDiscardHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDiscardHangarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hangarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(49, 49, 49)
                                            .addComponent(nameLabel))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(powerLabel)
                                                .addComponent(fuelLabel))))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(shieldPLabel)
                                        .addComponent(medalsLabel))
                                    .addGap(18, 18, 18)
                                    .addComponent(damagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(weaponsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(shieldsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbDiscardHangar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbMount)
                        .addGap(18, 18, 18)
                        .addComponent(jbDiscard)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(jLabel4)
                            .addComponent(shieldPLabel)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fuelLabel)
                            .addComponent(jLabel5)
                            .addComponent(medalsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(powerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(damagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weaponsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(shieldsScroll))
                .addGap(18, 18, 18)
                .addComponent(hangarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDiscard)
                    .addComponent(jbMount)
                    .addComponent(jbDiscardHangar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbMountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMountActionPerformed
        // TODO add your handling code here:
        MainView.controller.mountElements(hv.getSelectedWeapons(), hv.getSelectedShields());
    }//GEN-LAST:event_jbMountActionPerformed

    private void jbDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDiscardActionPerformed
        // TODO add your handling code here:
        MainView.controller.discardMountedElements(getSelectedWeapons(), getSelectedShields(), hv.getSelectedWeapons(), hv.getSelectedShields());
    }//GEN-LAST:event_jbDiscardActionPerformed

    private void jbDiscardHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDiscardHangarActionPerformed
        // TODO add your handling code here:
        MainView.controller.discardHangar();
    }//GEN-LAST:event_jbDiscardHangarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel damagePanel;
    private javax.swing.JLabel fuelLabel;
    private javax.swing.JPanel hangarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbDiscard;
    private javax.swing.JButton jbDiscardHangar;
    private javax.swing.JButton jbMount;
    private javax.swing.JLabel medalsLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel powerLabel;
    private javax.swing.JLabel shieldPLabel;
    private javax.swing.JPanel shieldsPanel;
    private javax.swing.JScrollPane shieldsScroll;
    private javax.swing.JPanel weaponsPanel;
    private javax.swing.JScrollPane weaponsScroll;
    // End of variables declaration//GEN-END:variables
}
